all:
	make clean
	make compile
	make run

compile:
	javac -classpath ".:/mnt/c/Users/runya/Desktop/Code/BluestacksCOCAutomationProject/src/resources/json-simple-1.1.1.jar:" CocBot.java

run:
	java -classpath ".:/mnt/c/Users/runya/Desktop/Code/BluestacksCOCAutomationProject/src/resources/json-simple-1.1.1.jar:" CocBot

clean:
	- rm *.class